"""Generate an evidence index, never infer live verification from implementation."""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from pubship.catalog import catalog  # noqa: E402
from pubship.hosted_catalog import HOSTED_CAPABILITIES  # noqa: E402

# These are related suites, not a claim that a file reference proves every
# possible input or provider effect. New tool families need explicit evidence.
SUITES = {
    "apply_monetization_write": (
        "test_monetization",
        "test_onetime_commerce",
        "test_legacy_products",
        "test_hosted_018_tools",
    ),
    "read_reporting": ("test_reporting", "test_hosted_tools"),
    "read_publisher": ("test_publisher_reads_engineering", "test_publisher_reads_adversarial"),
    "apply_purchase_operation": (
        "test_purchase_contracts",
        "test_purchase_transport",
        "test_purchase_service_adversarial",
        "test_hosted_019_tools",
    ),
    "apply_edit_write": (
        "test_edit_writes_engineering",
        "test_edit_writes_adversarial",
        "test_hosted_018_tools",
    ),
    "read_publisher_edit": ("test_publisher_edits", "test_publisher_edits_adversarial"),
    "apply_support_operation": (
        "test_support_contracts",
        "test_support_transport",
        "test_support_service_adversarial",
    ),
    "read_sensitive_publisher": (
        "test_publisher_reads_engineering",
        "test_publisher_reads_adversarial",
    ),
    "apply_appstore_operation": (
        "test_appstore_contracts",
        "test_appstore_transport",
        "test_appstore_adversarial",
        "test_hosted_020_loopback",
    ),
    "apply_artifact_upload": (
        "test_artifacts_engineering",
        "test_artifacts_adversarial",
        "test_hosted_020_loopback",
    ),
    "apply_account_access": (
        "test_account_access",
        "test_account_mcp_integration",
        "test_hosted_021_loopback",
    ),
    "apply_publisher_edit_operation": (
        "test_edit_lifecycle_engineering",
        "test_edit_lifecycle_adversarial",
        "test_hosted_017_http",
    ),
    "query_monetization": ("test_monetization", "test_onetime_commerce"),
    "apply_signing_operation": (
        "test_signing",
        "test_signing_adversarial",
        "test_hosted_021_loopback",
    ),
    "query_appstore": (
        "test_appstore_contracts",
        "test_appstore_transport",
        "test_hosted_020_loopback",
    ),
    "download_artifact": (
        "test_artifacts_engineering",
        "test_artifacts_adversarial",
        "test_hosted_020_loopback",
    ),
    "apply_internal_sharing_upload": ("test_sharing", "test_hosted_020_loopback"),
    "list_releases": ("test_core", "test_hosted_tools"),
    "apply_store_listing_update": (
        "test_listing_staging_engineering",
        "test_listing_staging_adversarial",
        "test_hosted_017_http",
    ),
    "apply_track_update": (
        "test_track_staging_engineering",
        "test_track_staging_adversarial",
        "test_hosted_017_http",
    ),
    "get_review": ("test_core", "test_hosted_tools"),
    "list_reviews": ("test_core", "test_hosted_tools"),
    "read_account_access": ("test_account_access", "test_hosted_021_loopback"),
    "read_report": ("test_core", "test_bulk_read_deadline"),
    "list_report_files": ("test_core", "test_hosted_tools"),
}

# Only methods explicitly named in the established live-read receipt. A returned
# empty collection verifies the request path, not every possible response shape.
LIVE_READS = {}


def render():
    methods = catalog()["methods"]
    supported = [item for item in methods if item["status"] == "implemented"]
    assert set(LIVE_READS) <= {item["id"] for item in supported}
    assert {item["id"] for item in supported} == set(HOSTED_CAPABILITIES)
    rows = []
    for item in sorted(supported, key=lambda item: item["id"]):
        tool = item["tool"]
        tests = SUITES[tool]
        for name in tests:
            if not (ROOT / "tests" / f"{name}.py").is_file():
                raise ValueError(f"Missing evidence file: {name}")
        links = ", ".join(f"[{name}](../tests/{name}.py)" for name in tests)
        live = (
            f"[Read receipt]({LIVE_READS[item['id']]})"
            if item["id"] in LIVE_READS
            else "Not verified live"
        )
        rows.append(f"| `{item['id']}` | {item['httpMethod']} | `{tool}` | {links} | {live} |")
    return (
        f"""# Provider verification index

Generated by `scripts/generate_verification.py` from the pinned catalog and explicit evidence mappings. Regenerate with the same command; `--check` detects drift.

All {len(supported)} supported methods are implemented locally and in hosted dispatch. **Implementation is not live-provider verification.** This index links related automated suites and any explicitly recorded Google reads. The suites use synthetic provider transports; links are navigation aids, not proof of every input, output or commercial entitlement. HTTP POST can be a read-only query, so the HTTP verb alone is not an effects classification. Follow each method's documented preparation and capability rules.

Only {len(LIVE_READS)} method paths currently have attributed live-read evidence here. This PubShip candidate has no attributed live reads. No live Google write is claimed. The provider-unsupported archive and policy-disabled voided-purchases methods remain non-callable and is excluded from the {len(supported)} rows. See the [safe provider acceptance plan](provider-acceptance.md), [catalog](api-methods.md), and [release/QA evidence](validation.md).

| Method | HTTP | Local tool | Related automated suites | Real Google evidence |
| --- | --- | --- | --- | --- |
"""
        + "\n".join(rows)
        + "\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "docs/provider-verification.md"
    result = render()
    if args.check:
        if not target.exists() or target.read_text() != result:
            raise SystemExit("Provider verification index drifted; regenerate it.")
    else:
        target.write_text(result)


if __name__ == "__main__":
    main()
