"""Reproduce the complete method catalog from pinned official discovery files."""

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from pubship.catalog import IMPLEMENTED  # noqa: E402
from pubship.coverage import (  # noqa: E402
    ACCOUNT_READ_METHODS,
    ACCOUNT_WRITE_METHODS,
    APPSTORE_READ_METHODS,
    APPSTORE_WRITE_METHODS,
    ARTIFACT_METHODS,
    EDIT_WRITE_METHODS,
    LEGACY_PRODUCT_WRITE_METHODS,
    MONETIZATION_QUERY_METHODS,
    MONETIZATION_WRITE_METHODS,
    POLICY_DISABLED_METHODS,
    PROVIDER_UNSUPPORTED_METHODS,
    PUBLISHER_READ_METHODS,
    PURCHASE_LIFECYCLE_METHODS,
    SENSITIVE_PUBLISHER_READ_METHODS,
    SHARING_METHODS,
    SIGNING_METHODS,
    SUPPORT_METHODS,
)


def walk(node):
    yield from node.get("methods", {}).values()
    for child in node.get("resources", {}).values():
        yield from walk(child)


def coverage_card(methods):
    """Render supported local coverage without treating unavailable APIs as work."""
    supported = [
        m for m in methods if m["status"] not in {"provider_unsupported", "policy_disabled"}
    ]
    implemented = sum(m["status"] == "implemented" for m in supported)
    total = len(supported)
    percent = implemented * 100 / total if total else 0
    families = []
    for api, label, color in (
        ("androidpublisher", "Android Publisher", "#16745c"),
        ("playdeveloperreporting", "Developer Reporting", "#3568b0"),
        ("storage", "Play bulk reports", "#8e642b"),
    ):
        group = [m for m in supported if m["api"] == api]
        count = sum(m["status"] == "implemented" for m in group)
        families.append((label, color, count, len(group)))
    cards = []
    for i, (label, color, count, size) in enumerate(families):
        x = 28 + i * 194
        cards.append(f'''<g transform="translate({x} 192)">
      <rect width="178" height="86" rx="12" fill="#ffffff" stroke="#d9e5df"/>
      <circle cx="17" cy="24" r="4" fill="{color}"/>
      <text x="30" y="29" font-size="23" font-weight="650">{count}<tspan font-size="16" font-weight="400" fill="#506b60"> / {size}</tspan></text>
      <text x="13" y="61" font-size="15" fill="#385548">{label}</text>
    </g>''')
    groups = "\n    ".join(cards)
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 620 330" role="img" aria-labelledby="title desc">
  <!-- Generated by scripts/generate_catalog.py. Do not edit by hand. -->
  <title id="title">PubShip: {implemented} of {total} supported methods implemented locally</title>
  <desc id="desc">{percent:.0f}% of the supported pinned API inventory has local implementations. Android Publisher, Developer Reporting and Play bulk reports. Privileged operations require opt-in. Hosted coverage and live Google verification are separate.</desc>
  <defs>
    <linearGradient id="surface" x2="1" y2="1"><stop stop-color="#f6fbf8"/><stop offset="1" stop-color="#edf5f0"/></linearGradient>
    <linearGradient id="progress"><stop stop-color="#16745c"/><stop offset="1" stop-color="#49a588"/></linearGradient>
  </defs>
  <rect x="1" y="1" width="618" height="328" rx="20" fill="url(#surface)" stroke="#cbded3"/>
  <g font-family="system-ui, -apple-system, sans-serif" fill="#173c30">
    <text x="28" y="36" font-size="15" font-weight="650" letter-spacing="1.4">PUBSHIP / LOCAL API COVERAGE</text>
    <text x="25" y="119" font-size="76" font-weight="700" letter-spacing="-3">{implemented}</text>
    <text x="185" y="91" font-size="23" font-weight="600">supported methods</text>
    <text x="185" y="119" font-size="18" fill="#506b60">Implemented. Ready to connect.</text>
    <text x="592" y="153" text-anchor="end" font-size="17" font-weight="600">{percent:.0f}%</text>
    <rect x="28" y="164" width="564" height="8" rx="4" fill="#d9e5df"/>
    <rect x="28" y="164" width="{564 * percent / 100:.3f}" height="8" rx="4" fill="url(#progress)"/>
    {groups}
    <text x="28" y="308" font-size="16" fill="#506b60">Your credentials. Explicit permissions. Open source.</text>
  </g>
</svg>
'''


def render():
    sources, methods, contracts = [], [], {}
    for api in ["androidpublisher", "playdeveloperreporting", "storage"]:
        path = ROOT / "api/discovery" / f"{api}.json"
        raw = path.read_bytes()
        doc = json.loads(raw)
        if api != "storage":
            contracts[api] = {"baseUrl": doc["baseUrl"], "schemas": doc["schemas"]}
        sources.append(
            {
                "api": api,
                "version": doc["version"],
                "revision": doc.get("revision"),
                "url": f"https://{api}.googleapis.com/$discovery/rest?version={doc['version']}",
                "sha256": hashlib.sha256(raw).hexdigest(),
                "scope": "Play bulk-report objects.list/get only"
                if api == "storage"
                else "all methods",
            }
        )
        for method in walk(doc):
            if api == "storage" and method["id"] not in {
                "storage.objects.list",
                "storage.objects.get",
            }:
                continue
            item = {
                key: method[key]
                for key in [
                    "id",
                    "httpMethod",
                    "path",
                    "description",
                    "parameters",
                    "request",
                    "response",
                    "scopes",
                    "supportsMediaUpload",
                    "supportsMediaDownload",
                    "useMediaDownloadService",
                    "mediaUpload",
                ]
                if key in method
            }
            item.update(
                {
                    "api": api,
                    "deprecated": bool(method.get("deprecated")),
                    "status": "implemented"
                    if method["id"] in IMPLEMENTED
                    else (
                        "provider_unsupported"
                        if method["id"] in PROVIDER_UNSUPPORTED_METHODS
                        else "policy_disabled"
                        if method["id"] in POLICY_DISABLED_METHODS
                        else "coming_soon"
                    ),
                    "tool": IMPLEMENTED.get(method["id"]),
                }
            )
            if method["id"] in POLICY_DISABLED_METHODS:
                item["implementation_scope"] = (
                    "Disabled by project policy. Voided-purchase data is not exposed to MCP clients."
                )
            if method["id"] in PROVIDER_UNSUPPORTED_METHODS:
                item["implementation_scope"] = (
                    "Google explicitly states that subscription archiving is not supported. Cataloged for completeness; no callable tool or implementation promise."
                )
            if method["id"] in MONETIZATION_QUERY_METHODS:
                item["implementation_scope"] = (
                    "Local fixed read-only POST with scoped nested identities. One provider response; conversions do not save prices. Hosted access requires separate connection consent."
                )
            if method["id"] in MONETIZATION_WRITE_METHODS:
                item["implementation_scope"] = (
                    "Local direct live subscription and modern one-time-product mutations with independent app/method opt-ins, acknowledged effects, single-use preparation, original credential, full observed-resource preflight and honest readback. No implicit creation, subscriber cohort migration, retry or rollback. Modern one-time upserts require explicit allowMissing and creation-capable bodies; force/cancel effects are disclosed. Top-level explicit masks and bounded batches; provider validation still applies."
                )
            if method["id"] in LEGACY_PRODUCT_WRITE_METHODS:
                item["implementation_scope"] = (
                    "Local managed-product compatibility only; legacy subscriptions rejected. Exact commerce app/method opt-ins; full-update upsert additionally requires insert grant. Explicit auto-conversion, original-credential single-use apply, full observations and qualified outcomes; no automatic retries. Hosted access requires separate connection consent."
                )
            if method["id"] in PUBLISHER_READ_METHODS:
                item["implementation_scope"] = (
                    "Local fixed GET for explicitly allowlisted apps. One page, no media download or "
                    "automatic pagination. Provider fields and missing data preserved. Hosted consent expansion is separate."
                )
            if method["id"] in PURCHASE_LIFECYCLE_METHODS:
                item["implementation_scope"] = (
                    "Local reviewed purchase/order actions, external transaction reports or subscriber price migrations with separate exact family grants and sensitive-read scope for customer observations. Original credential and private copied intent, single-use IDs, retained native preconditions, redacted output and bounded preflight/readback. No automatic retry or guaranteed refund decision/cohort completion. Local opt-ins never grant hosted authority. External reporting never transfers funds; legacy subscription actions require an explicit single-item subscription identity."
                )
            if method["id"] in SIGNING_METHODS:
                item["implementation_scope"] = (
                    "Local enterprise self-hosted Cloud KMS signing with independent exact app, method and key-version grants. Public certificate parsing and hash correlation, original credential and single-use reviewed apply. Standard Google-managed signing remains Console-only. No baseline, readback, rollback or automatic retry; eligibility, KMS association and lineage validation remain Google-controlled."
                )
            if method["id"] in ACCOUNT_READ_METHODS | ACCOUNT_WRITE_METHODS:
                item["implementation_scope"] = (
                    "Local account administration with independent developer and method scopes. Account reads include personal data. Writes additionally require exact user/app scopes and permission ceilings, bounded complete users.list baselines, rejection of partial targets and original-credential single-use execution. No automatic retry; observed state is not atomic or proof of effective permission propagation."
                )
            if method["id"] in APPSTORE_READ_METHODS | APPSTORE_WRITE_METHODS:
                item["implementation_scope"] = (
                    "Local eligible third-party app-store integration with independent exact store, target and method grants. Bounded catalog reads and prepared writes; uploads use private immutable media snapshots. Updates submit for review immediately and default to published state. No hosted-app baseline/readback, automatic retry or approval guarantee. Policy declarations are operator supplied."
                )
            if method["id"] in SUPPORT_METHODS:
                item["implementation_scope"] = (
                    "Local direct support operation with independent package/exact-method grants, operator-supplied content, acknowledged effects and original-credential single-use execution. Review and existing-recovery baselines rechecked; no baseline for creates/declarations. Supported readback reported separately; Data safety has no read API. No retries or production-publication guarantee. Local opt-ins never grant hosted authority."
                )
            if method["id"] in SHARING_METHODS:
                item["implementation_scope"] = (
                    "Local direct internal sharing upload, not edit staging or production release. Explicit artifact package/exact-method grants and upload root; bounded private snapshot, original credential and single-use execution. Google re-signs artifacts; source and provider hashes differ in meaning. No retry or URL fetch, and no separate artifact readback endpoint."
                )
            if method["id"] in ARTIFACT_METHODS:
                item["implementation_scope"] = (
                    "Local artifact operation requiring independent package and exact-method opt-ins. "
                    "Binary files use explicit roots and bounded streaming. Uploads bind private file snapshots "
                    "to reviewed single-use preparations and original credentials; simple media only, no automatic "
                    "retry or edit commit. Downloads save files locally using fixed Google media routes. "
                    "Local size/protocol restrictions and incomplete provider baseline verification are documented."
                )
            if method["id"] in EDIT_WRITE_METHODS:
                item["implementation_scope"] = (
                    "Local existing-edit resource write requiring GOOGLE_PLAY_EDIT_WRITE_PACKAGES "
                    "within read scope and an exact GOOGLE_PLAY_EDIT_WRITE_METHODS allowlist. "
                    "Explicit effects acknowledgement, strict local body limits, single-use preparation, "
                    "full resource/edit-metadata preflight and mandatory readback with the original credential. "
                    "Mutation success and observation success are separate. No retries, uploads or implicit commit."
                )
            if method["id"] in SENSITIVE_PUBLISHER_READ_METHODS:
                item["implementation_scope"] = (
                    "Local fixed GET requiring GOOGLE_PLAY_SENSITIVE_READ_PACKAGES within read allowlists. "
                    "Returns authorized provider data, which may contain identities, tokens and financial details; "
                    "request URLs/identifiers are not echoed in wrapper metadata or errors. Hosted access requires separate connection consent."
                )
            if api == "storage":
                item["implementation_scope"] = (
                    "Allowlisted app; installs, ratings and store_performance reports only. Not a generic Cloud Storage interface."
                )
            if method["id"] == "androidpublisher.edits.tracks.update":
                item["implementation_scope"] = (
                    "Local stdio opt-in via GOOGLE_PLAY_TRACK_PACKAGES within read allowlists. "
                    "Full explicit releases replacement in an existing edit, with whole-track acknowledgement "
                    "and a single-use preparation. PUT only; no implicit edit creation, validation or commit. "
                    "Observed full-track drift checks are not atomic; hosted staging requires separate connection consent."
                )
            if method["id"] == "androidpublisher.edits.listings.patch":
                item["implementation_scope"] = (
                    "Local stdio opt-in: title, shortDescription and fullDescription in an existing edit. "
                    "Requires GOOGLE_PLAY_WRITE_PACKAGES and a single-use prepared operation. "
                    "No implicit edit creation or commit. Hosted staging requires separate connection consent."
                )
            if method["id"] in {
                "androidpublisher.edits.insert",
                "androidpublisher.edits.validate",
                "androidpublisher.edits.delete",
                "androidpublisher.edits.commit",
            }:
                item["implementation_scope"] = (
                    "Local stdio opt-in via GOOGLE_PLAY_EDIT_PACKAGES, within write/read allowlists. "
                    "Requires explicit effects acknowledgement and a single-use preparation. "
                    "Commit always uses ERROR_IF_IN_REVIEW; no full-content drift guarantee. Hosted execution requires separate connection consent."
                )
            if item.get("status") == "implemented" and "implementation_scope" in item:
                item["implementation_scope"] += (
                    " This describes the local implementation; hosted availability and exact "
                    "connection authority are reported separately in execution metadata."
                )
            methods.append(item)
    methods.sort(key=lambda item: item["id"])
    assert len({m["id"] for m in methods}) == len(methods), "Duplicate method IDs"
    assert set(IMPLEMENTED) <= {m["id"] for m in methods}, (
        "Implemented method absent from discovery"
    )
    data = json.dumps({"sources": sources, "methods": methods}, indent=2, sort_keys=True) + "\n"
    lines = [
        "# Complete API method catalog",
        "",
        "Generated by `scripts/generate_catalog.py`; do not edit by hand.",
        "",
        "**All** methods from the pinned Android Publisher v3 and Play Developer Reporting v1beta1 definitions are listed below, including deprecated methods. Two Cloud Storage methods support Play bulk reports; the rest of Cloud Storage is outside this project's scope.",
        "",
        "Policy disabled means deliberately non-callable and excluded from supported coverage. Voided-purchase data is never returned to MCP clients. Provider unsupported means Google explicitly does not support the operation; it remains cataloged without a callable tool or implementation promise. Coming soon means planned, not callable, and carries no release-date promise. Implemented means a tested tool exists (some require explicit local enablement); live verification and scope limits are documented separately in [validation.md](validation.md).",
        "",
    ]
    for source in sources:
        api = source["api"]
        rows = [m for m in methods if m["api"] == api]
        count = sum(m["status"] == "implemented" for m in rows)
        lines += [
            f"## {api} ({source['version']})",
            "",
            f"{len(rows)} methods · {count} implemented · {sum(m['status'] == 'coming_soon' for m in rows)} coming soon · {sum(m['status'] == 'provider_unsupported' for m in rows)} provider unsupported · discovery revision `{source['revision']}`.",
            "",
            f"[Official definition]({source['url']}) · Snapshot SHA-256: `{source['sha256']}`",
            "",
            "| Method | HTTP | Endpoint | Status | Tool | Deprecated |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for method in rows:
            status = {
                "implemented": "Implemented",
                "coming_soon": "Coming soon",
                "provider_unsupported": "Provider unsupported",
                "policy_disabled": "Disabled by policy",
            }[method["status"]]
            lines.append(
                f"| `{method['id']}` | {method['httpMethod']} | `{method['path']}` | {status} | {method['tool'] or ';'} | {'Yes' if method['deprecated'] else ';'} |"
            )
        lines.append("")
    return {
        ROOT / "src/pubship/methods.json": data,
        ROOT / "src/pubship/contracts.json": json.dumps(contracts, indent=2, sort_keys=True) + "\n",
        ROOT / "docs/api-methods.md": "\n".join(lines).rstrip() + "\n",
        ROOT / "docs/assets/api-coverage.svg": coverage_card(methods),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Fail if generated files differ; no network calls."
    )
    args = parser.parse_args()
    stale = []
    for path, text in render().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("Stale generated catalog: " + ", ".join(stale))


if __name__ == "__main__":
    main()
